//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_ASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public int OrderID { get; set; }
        public string Item { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual CustomerTable CustomerTable { get; set; }
    }
}
